[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
citizenhub_program = "GcwrHG7nXB2Tz9P2GcwYfvgTvMdN3vkVWBhMzvEsZfhk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./secret/wallet-keypair.json"

[scripts]
test = "anchor test"
